/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>


typedef enum
{
	IT_Ctrl_Disable_IT_And_Conf_Fault_Handlers = 0,
	IT_Ctrl_Disable_IT_And_All_Fault_Handlers,
	IT_Ctrl_Enable_IT_And_Conf_Fault_Handlers,
	IT_Ctrl_Enable_IT_And_All_Fault_Handlers,
} IT_Control;

__attribute__((always_inline)) inline void iterrupt_control(IT_Control it_control)
{
#ifdef __ARM_ARCH_7EM__
	switch (it_control) {
		case IT_Ctrl_Disable_IT_And_Conf_Fault_Handlers:
			__asm__ inline volatile ("cpsid i");
			break;
		case IT_Ctrl_Disable_IT_And_All_Fault_Handlers:
			__asm__ inline volatile ("cpsid f");
			break;
		case IT_Ctrl_Enable_IT_And_Conf_Fault_Handlers:
			__asm__ inline volatile ("cpsie i");
			break;
		case IT_Ctrl_Enable_IT_And_All_Fault_Handlers:
			__asm__ inline volatile ("cpsie f");
			break;
		default:
			break;
	}
#else
	#error "Unsupported processor! Supported cpu's: cortex-m4"
#endif
}


int main(void)
{

	iterrupt_control(IT_Ctrl_Disable_IT_And_All_Fault_Handlers);
	iterrupt_control(IT_Ctrl_Enable_IT_And_All_Fault_Handlers);

    /* Loop forever */
	for(;;);
}
